allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  svelte-preprocess: true

minimumReleaseAgeExclude:
  - astro@7.0.3

packages:
  - packages/*
  - examples/*
  - web
