name: Release

on:
  push:
    tags:
      - "@adraw/*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
